import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Homepage/Navbar";
import Footer from "./components/footer/Footer";
import QueryProvider from "./components/queryProvider/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ShorolShop-The-Online-Bazar-for-Villagers ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header className="sticky  top-0 z-10">
          <Navbar />
        </header>

        <QueryProvider>
          <main className="w-11/12 mx-auto">{children}</main>
        </QueryProvider>
        <footer className="w-11/12 mx-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
