import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Homepage/Navbar";
import Footer from "./components/footer/Footer";
import QueryProvider from "./components/queryProvider/QueryProvider";
import Products from "./products/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-11/12 mx-auto`}
      >
        <header className="sticky top-0 z-10">
          <Navbar />
        </header>

        <QueryProvider>
          <main>{children}</main>
        </QueryProvider>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
