import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import NextAuthSessionProvider from "@/provider/NextAuthSessionProvider";
import QueryProvider from "../components/queryProvider/QueryProvider";
import Footer from "../components/footer/Footer";

export const metadata = {
  title: "Get Start With SorolShop ",
  description: "Generated by Md Josim Uddin ",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          <QueryProvider>
            <main className="w-11/12 mx-auto">{children}</main>
          </QueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
