import "@/app/globals.css";
import NextAuthSessionProvider from "@/provider/NextAuthSessionProvider";
import QueryProvider from "../components/queryProvider/QueryProvider";
import Sidebar from "./overview/Sidebar";

export const metadata = {
  title: "Wellcome to Dashboard | SorolShop ",
  description: "Generated by Md Josim Uddin ",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          <QueryProvider>
            <div className="grid grid-cols-12">
              <aside className="col-span-3">
                <Sidebar />
              </aside>
              <main className="md:col-span-9 col-span-12">{children}</main>
            </div>
          </QueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
